// This file is generated by Slice Machine. Update with care!

import AnotherSlice from './AnotherSlice';
import MySlice from './MySlice';

export {
	AnotherSlice,
	MySlice,
};

export const components = {
	another_slice: AnotherSlice,
	my_slice: MySlice,
};
